// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv0JXpU20p4t-2bNPKraP-Eos8RImoJwk',
    appId: '1:474478825939:web:d04add2225e0ed20ac9f26',
    messagingSenderId: '474478825939',
    projectId: 'usaf-ty',
    authDomain: 'usaf-ty.firebaseapp.com',
    storageBucket: 'usaf-ty.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp_AdGk4ZDEfzdWcMzZ0LytF1lREJilqI',
    appId: '1:474478825939:android:2a6989dde1cc8b09ac9f26',
    messagingSenderId: '474478825939',
    projectId: 'usaf-ty',
    storageBucket: 'usaf-ty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiMKPbMOM2Kv92el5tZTOlOMWLbbW7AhA',
    appId: '1:474478825939:ios:aa257227dd4b76cbac9f26',
    messagingSenderId: '474478825939',
    projectId: 'usaf-ty',
    storageBucket: 'usaf-ty.appspot.com',
    iosBundleId: 'com.example.usaficity',
  );
}
